version: '1'

services:
  djangoapp:
    build: .
    command: bash -c "python gpsautotracker/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/src/gpsautotracker/staticfiles
      - media_volume:/opt/services/djangoapp/media
#    expose:
#      - "8000"
    networks:
    - nginx_network

  nginx:
    image: nginx:latest
    ports:
    - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/staticfiles
      - media_volume:/opt/services/djangoapp/media
    depends_on:
    - djangoapp
    networks:
    - nginx_network

volumes:
  static_volume:
  media_volume: